name: Gemini
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - expat=2.7.3
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libiconv=1.16
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.3
  - python=3.9
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - flask
    - flask-cors
    - google-genai
    - PyPDF2
    - requests
prefix: /Users/alinaliu18/Gemini-Hackathon/env
